#!/usr/bin/env ruby

require 'gli'
require "formatafacil"

include GLI::App

program_desc 'Gera documentos na norma da ABNT a partir de textos escritos em Asciidoc.'

version Formatafacil::VERSION

subcommand_option_handling :normal
arguments :strict
